create table if not exists public.banco_preguntas (
  id bigint generated by default as identity primary key,
  tema text,
  dificultad text check (dificultad in ('basico', 'intermedio', 'avanzado')),
  enunciado text not null,
  recurso_visual_url text,
  recurso_visual_alt text,
  opcion_a text not null,
  opcion_b text not null,
  opcion_c text,
  opcion_d text,
  respuesta_correcta text not null check (respuesta_correcta in ('A', 'B', 'C', 'D')),
  explicacion text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.simulador_preguntas
add column if not exists tema text,
add column if not exists dificultad text check (dificultad in ('basico', 'intermedio', 'avanzado'));

drop trigger if exists banco_preguntas_set_updated_at on public.banco_preguntas;
create trigger banco_preguntas_set_updated_at
before update on public.banco_preguntas
for each row
execute function public.set_updated_at();
