alter table public.lecciones
add column if not exists orden integer not null default 1;

update public.lecciones
set orden = ordered.position
from (
  select id, row_number() over (partition by curso_id order by coalesce(created_at, now()), id) as position
  from public.lecciones
) as ordered
where public.lecciones.id = ordered.id
  and public.lecciones.orden = 1;

alter table public.leccion_contenidos
add column if not exists acepta_entrega boolean not null default false;

create table if not exists public.entregas_actividades (
  id bigint generated by default as identity primary key,
  contenido_id bigint not null references public.leccion_contenidos(id) on delete cascade,
  estudiante_id uuid not null references auth.users(id) on delete cascade,
  archivo_url text,
  comentario text,
  nota numeric(5,2),
  retroalimentacion text,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'entregado', 'vencido', 'calificado')),
  entregado_en timestamptz,
  calificado_en timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (contenido_id, estudiante_id)
);

drop trigger if exists entregas_actividades_set_updated_at on public.entregas_actividades;

create trigger entregas_actividades_set_updated_at
before update on public.entregas_actividades
for each row
execute function public.set_updated_at();
