create table if not exists public.leccion_contenidos (
  id bigint generated by default as identity primary key,
  leccion_id bigint not null references public.lecciones(id) on delete cascade,
  titulo text not null,
  descripcion text,
  tipo text not null check (tipo in ('guia', 'simulador', 'prueba', 'video', 'enlace')),
  contenido_url text,
  orden integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists leccion_contenidos_set_updated_at on public.leccion_contenidos;

create trigger leccion_contenidos_set_updated_at
before update on public.leccion_contenidos
for each row
execute function public.set_updated_at();
