create table if not exists public.simuladores (
  id bigint generated by default as identity primary key,
  contenido_id bigint not null unique references public.leccion_contenidos(id) on delete cascade,
  titulo text,
  instrucciones text,
  duracion_minutos integer not null default 20 check (duracion_minutos > 0),
  mostrar_resultado_inmediato boolean not null default true,
  mezclar_preguntas boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.simulador_preguntas (
  id bigint generated by default as identity primary key,
  simulador_id bigint not null references public.simuladores(id) on delete cascade,
  enunciado text not null,
  opcion_a text not null,
  opcion_b text not null,
  opcion_c text,
  opcion_d text,
  respuesta_correcta text not null check (respuesta_correcta in ('A', 'B', 'C', 'D')),
  explicacion text,
  orden integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.simulador_intentos (
  id bigint generated by default as identity primary key,
  simulador_id bigint not null references public.simuladores(id) on delete cascade,
  estudiante_id uuid not null references auth.users(id) on delete cascade,
  puntaje integer not null default 0,
  total_preguntas integer not null default 0,
  tiempo_segundos integer,
  completado_en timestamptz not null default timezone('utc', now()),
  respuestas jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists simuladores_set_updated_at on public.simuladores;
create trigger simuladores_set_updated_at
before update on public.simuladores
for each row
execute function public.set_updated_at();

drop trigger if exists simulador_preguntas_set_updated_at on public.simulador_preguntas;
create trigger simulador_preguntas_set_updated_at
before update on public.simulador_preguntas
for each row
execute function public.set_updated_at();

drop trigger if exists simulador_intentos_set_updated_at on public.simulador_intentos;
create trigger simulador_intentos_set_updated_at
before update on public.simulador_intentos
for each row
execute function public.set_updated_at();
